DROP DATABASE IF EXISTS employees_db;
CREATE DATABASE employees_db;

USE employees_db;

CREATE TABLE DEPARTMENT (
    ID      INT NOT NULL AUTO_INCREMENT,
    NAME    VARCHAR(30) NOT NULL,

    PRIMARY KEY (ID)
);

CREATE TABLE ROLE (
    ID              INT NOT NULL AUTO_INCREMENT,
    TITLE           VARCHAR(30) NOT NULL,
    SALARY          DECIMAL, 
    DEPARTMENT_ID   INT NOT NULL,

    PRIMARY KEY (ID),
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(ID)    
);

CREATE TABLE EMPLOYEE (
    ID              INT NOT NULL AUTO_INCREMENT,
    FIRST_NAME      VARCHAR(30) NOT NULL,
    LAST_NAME       VARCHAR(30) NOT NULL,
    IS_MANAGER      BOOLEAN DEFAULT FALSE,
    ROLE_ID         INT DEFAULT 0 NULL, 
    MANAGER_ID      INT,

    PRIMARY KEY (ID),
    FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID),
    FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEE(ID) ON DELETE CASCADE ON UPDATE NO ACTION
);

